ALTER TABLE payments
ADD COLUMN IF NOT EXISTS provider VARCHAR(64);

ALTER TABLE payments
ADD COLUMN IF NOT EXISTS provider_payment_method_id VARCHAR(128);

ALTER TABLE payments
ADD COLUMN IF NOT EXISTS cardholder_name VARCHAR(255);

ALTER TABLE payments
ADD COLUMN IF NOT EXISTS card_brand VARCHAR(64);

ALTER TABLE payments
ADD COLUMN IF NOT EXISTS card_last4 VARCHAR(4);

ALTER TABLE payments
ADD COLUMN IF NOT EXISTS expiry_month INT;

ALTER TABLE payments
ADD COLUMN IF NOT EXISTS expiry_year INT;

ALTER TABLE payments
ADD COLUMN IF NOT EXISTS billing_postal_code VARCHAR(32);

ALTER TABLE payments
ADD COLUMN IF NOT EXISTS is_dummy BOOLEAN NOT NULL DEFAULT TRUE;
