ktor:
    application:
        modules:
            - flightbooking.ApplicationKt.module
    deployment:
        port: 8080

database:
    jdbcUrl: "jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require"
    username: "postgres.ldjdhvytfyxaqmdebvco"
    password: "0VS5oiDFa9NaLN3V"
    driverClassName: org.postgresql.Driver
    maximumPoolSize: 10

seed:
    runOnStartup: ${?RUN_CSV_SEED}
